const ADD ="ADD_MENU"
const ADDNEST='ADD_CHILDMENU'
const DELETE="DELETE_MENU"
const DELETENEST="DELETE_CHILDMENU"
const EDIT ="EDIT_MENU"
const EDITNEST="EDIT_CHILDMENU"


export default {ADD,ADDNEST,DELETE,DELETENEST,EDIT,EDITNEST}
