"use client"
import App from './App'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout( ) {
  return (
    <html lang="en">
      <body  >
      <App/>
       </body>
    </html>
  )
}
